name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install flask pytest
    - name: Run tests
      run: |
        echo "Testing Flask app response"
        python -c "import app; print(app.app.test_client().get('/').json)"
    - name: Build Docker image
      run: docker build -t devops-demo-app .
